name: Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Android, iOS, Web Build

    env:
      my_secret: "${{secrets.WORKFLOW_TOKEN}}"
      my_email: "mahmoodzadeh.masoud@gmail.com"
      my_name: "Masoud Mahmoodzadeh"
      my_tag: "v1.0.${{github.run_number}}"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          echo "Your Repo is $my_repo"
          echo "Your secrect token is $my_secret"
          echo "Your email is $my_email"
          echo "Your name is $my_name"
      # Setup Java environment.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18.x"

      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.3.8"

#      - run: flutter config --enable-android
#      - run: flutter config --enable-ios
#      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get

      # Flutter android apk build command. s
#      - run: flutter build apk
      - run: flutter build apk --split-per-abi
#      - run: flutter build appbundle
###
      #      # Flutter ios ipa build command.
      #      - run: |
      #          flutter build ios --no-codesign
      #          cd build/ios/iphoneos
      #          mkdir Payload
      #          cd Payload
      #          ln -s ../Runner.app
      #          cd ..
      #          zip -r app.ipa Payload
      # Flutter web release command.
      #      - run: flutter build web --web-renderer html --release
      #      - run: |
      #          cd build/web
      #          git init
      #          git config --global user.email "$my_email"
      #          git config --global user.name "$my_name"
      #          git status
      #          git remote add origin https://"$my_secret"@github.com/"$my_repo"
      #          git checkout -b gh-pages
      #          git add --all
      #          git commit -m "update"
      #          git push origin gh-pages -f
      # Upload assets to release
      - name: Create a Release APK
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          title: "Test Title"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
        env:
          GITHUB_REPOSITORY: masoudmahmoodzadeh/Flutter-Github-Action-Example